/** Hub cards. Full articles live in topics.js — each card opens /materials/:id. */

function c(id, title, teaser, grade, free, to) {
  return { id, title, teaser, kind: "article", to: to || "/materials/" + id, grade, free };
}

export const TRACKS = [
  {
    id: "requirements",
    title: "Требования",
    kicker: "от боли до постановки",
    blurb: "Need, User Story, Use Case, BRD, NFR, трассировка, Jira. Каждая карточка — полная статья из шести частей и инфографика, не тизер.",
    cards: [
      c("req-need", "Что такое требование", "Проверяемое правило: условие, объект, исход. Slack-цитата — не требование.", "intern", true),
      c("req-levels", "Уровни требований", "Бизнес → стейкхолдер → решение → тест. Kafka — не need.", "intern", true),
      c("req-story", "User Story и Use Case", "Роль и ценность. Актёр, основной поток, ошибка шлюза.", "intern", true),
      c("req-ac", "Acceptance Criteria", "Given / When / Then, которые QA не перепишет с нуля.", "intern", true),
      c("req-brd", "BRD: зачем меняемся", "Документ про ценность и границы. Не список экранов.", "junior", false),
      c("req-nfr", "NFR: объём, ночь, ключ", "Нефункциональное — тоже тест. Идемпотентность сюда же.", "intern", true),
      c("req-trace", "Трассировка", "Need → история → правило → тест. Дырки видны до релиза.", "intern", true),
      c("req-stakeholders", "Карта стейкхолдеров", "Кто пользуется, кто вето, кого забыли в ночную смену.", "intern", true),
      c("req-quality", "Качество формулировки", "Сильный глагол, два наблюдаемых места. «Корректно» — брак.", "intern", true),
      c("req-jira", "Постановка в Jira и Confluence", "Тикет, который можно провалить. Страница — не кладбище PDF.", "intern", true),
      c("int-task", "Постановка на разработчика", "Need, ключ, ошибка, мастер поля. Не «сделайте REST».", "intern", true),
      c("req-validate", "Проверка и торг требования", "Не эмодзи в чате. Тест, люди, how можно сменить.", "intern", true),
      c("req-lifecycle", "Жизнь требования и CR", "Состояния правила. Частичный capture — не комментарий в Done.", "intern", true),
      c("req-test-analysis", "От AC к кейсам QA", "GWT размножается в выстрелы: повтор, отказ, UNKNOWN.", "intern", true),
      c("req-estimate", "Оценка футболками", "S/M/L по дырам в правиле, не часы из воздуха.", "junior", true),
      c("req-gost-34602", "ГОСТ 34.602 как конверт", "ТЗ для приёмки по описи. Не вместо User Story.", "junior", true),
    ],
  },
  {
    id: "integrations",
    title: "Интеграции",
    kicker: "контракт, не JSON",
    blurb: "Повтор, таймаут, маппинг, DLQ, очереди, SOAP/gRPC, OAuth. Статья сначала, стол потом.",
    cards: [
      c("int-idem", "Интеграции и идемпотентность", "Шлюз повторяет — это ветка контракта. Два ключа: вход и выход.", "intern", true),
      c("int-sync", "Синхрон и асинхрон", "Ждём ответ сейчас или кладём событие. Выбор — NFR, не мода.", "intern", true),
      c("int-webhook", "Webhook против опроса", "Сосед стучится к вам или вы его спрашиваете. Повтор обязателен.", "intern", true),
      c("int-timeout", "Таймаут и UNKNOWN", "Нет ответа ≠ нет эффекта. Касса не рисует SUCCESS.", "intern", true),
      c("int-map", "Маппинг полей и DLQ", "Их id ≠ наш id. Яд не глотать молча — мёртвая очередь.", "junior", false),
      c("int-queue", "Очереди: Kafka и Rabbit", "Лог событий vs брокер задач. SA описывает повтор и DLQ, не брокер.", "junior", false),
      c("int-soap", "SOAP, REST и gRPC", "Три конверта. Банк-сосед часто XML. Учебный зал — JSON.", "intern", true),
      c("int-oauth", "OAuth и JWT: введение", "Кто вы и что можно. Токен — не «секрет в теле перевода».", "intern", true),
      c("int-task-2", "Постановка на интеграцию", "Need, payload, 409, мастер поля.", "intern", true, "/materials/int-task"),
    ],
  },
  {
    id: "restapi",
    title: "REST",
    kicker: "дизайн и коды",
    blurb: "Ресурс, метод, HTTP-код, версия, живой провод в пет. Идемпотентность — в той же статье, не сноска.",
    cards: [
      c("rest-http", "REST и HTTP", "Глагол, 409, ключ. Почему 200 + success:false ломает ретраи.", "intern", true),
      c("rest-codes", "HTTP-коды для SA", "Что повторять, что остановить, что чинить валидацию.", "intern", true),
      c("rest-resource", "Дизайн ресурса", "Кошелёк и перевод — сущности. Не /doTransferNow.", "intern", true),
      c("rest-idem", "Идемпотентность POST", "Ключ на попытку человека. Второй выстрел — тот же эффект.", "intern", true),
      c("rest-version", "Версионирование API", "Ломающее поле — новая версия или явный контракт.", "junior", false),
      c("rest-errors", "Тело ошибки", "Код + машина + человеку. Не HTML 500 в JSON-клиент.", "intern", true),
      c("rest-explorer", "Проводник запросов", "Как Postman, но в зале: вкладка API учебного банка.", "intern", true),
      c("api-openapi", "OpenAPI 3 как артефакт", "YAML на capture холда: ключ, 201, 409. Не скрин Swagger.", "junior", true),
      c("api-postman", "Коллекция как живой контракт", "Три выстрела: auth, capture, повтор. /pet?tab=api.", "intern", true),
      c("api-asyncapi", "AsyncAPI для топиков", "Повтор доставки не пишет вторую DR. Ключ в сообщении.", "junior", true),
      c("api-graphql", "GraphQL: когда не REST", "Карточка — query. Деньги — REST с 409.", "junior", true),
      c("api-schema", "JSON Schema и XSD", "Забор на входе. Строка-сумма — 422, не журнал.", "junior", true),
      c("api-pagination", "Страницы, курсор, фильтры", "Живой журнал — курсор. SUCCESS ≠ холд.", "intern", true),
    ],
  },
  {
    id: "database",
    title: "БД и SQL",
    kicker: "на живом банке",
    blurb: "ER, JOIN, многие-ко-многим, индекс, JSON↔таблица. Не лекция про установку клиента.",
    cards: [
      c("db-sql", "SQL к пет-БД", "Какая строка врёт в карточке. WHERE, HAVING, не UPDATE balance.", "intern", true),
      c("db-er", "ER против класса", "Сущность данных ≠ объект кода. Холд — не метод Wallet.", "intern", true),
      c("db-keys", "Ключи и уникальность", "payment_id один раз. Без уникальности дубль легален.", "intern", true),
      c("db-join", "JOIN на пет-банке", "Склеить кошелёк и ноги. Без ключа — декартово враньё.", "intern", true),
      c("db-m2m", "Многие-ко-многим", "Клиент ↔ роль, платёж ↔ тег. Связующая таблица, не CSV в ячейке.", "intern", true),
      c("db-index", "Индексы для аналитика", "Чем ищут ночью. Не «добавь индекс везде».", "junior", false),
      c("db-json", "JSON и таблица", "Поле в JSON удобно до первого отчёта. Потом больно.", "intern", true),
      c("db-layers", "Три слоя данных", "Смысл → сущности → Postgres. Не сразу CREATE.", "intern", true),
      c("db-window", "Оконные функции SQL", "В зале — GROUP BY на журнал. На работе окно оставляет сами строки.", "junior", true),
      c("db-cte", "CTE и подзапросы", "На работе WITH с именем шага. В зале — те же шаги и живой GROUP BY.", "junior", true),
      c("db-migrate", "Миграция схемы как требование", "Расширить, заполнить, unique. Не сразу NOT NULL.", "junior", true),
      c("db-dwh", "DWH, ETL и зерно", "Строка отчёта ≠ холд. Оборот только из ног.", "junior", true),
    ],
  },
  {
    id: "architecture",
    title: "Архитектура",
    kicker: "схема и деньги",
    blurb: "BPMN as-is, UML, C4, холд, журнал, P2P, IBAN. Коробки без денег — слайд, не контур.",
    cards: [
      c("arch-bpmn", "BPMN as-is", "Дорожки смены, костыль руками. To-be без as-is — фантазия.", "junior", false),
      c("arch-bpmn-mistakes", "Ошибки BPMN", "Павлин из блоков, актёр «система», auth = проводка.", "junior", false),
      c("arch-uml", "UML, который читают", "Состояния платежа, не павлин из стрелок.", "junior", false),
      c("arch-seq", "Диаграмма последовательности", "Кто кого зовёт. ACS, касса, ядро — по времени.", "intern", true),
      c("arch-c4", "C4 контура", "Контекст и контейнеры. Где холд, где журнал, где ключ.", "junior", false),
      c("arch-hold", "Холд и журнал", "Отложенная сумма ≠ проводка. Касса SUCCESS ещё не книга.", "intern", true),
      c("arch-journal", "Журнал и trial", "Две ноги, одна сумма. Дыра — отсутствующая нога.", "intern", true),
      c("arch-p2p", "P2P внутри банка", "DR отправителя, CR получателя. Повтор без ключа — учебный баг.", "intern", true),
      c("arch-iban", "Входящий IBAN", "Nostro и клиент. Непонятный счёт — suspense, не «накинем».", "intern", true),
      c("arch-styles", "Монолит, SOA, MSA, EDA", "Стиль по шву двух ног, не по моде.", "middle", false),
      c("arch-eip", "EIP: подписка, переводчик, маршрутизатор", "Выкройка на стрелке. Не логотип брокера.", "middle", false),
      c("arch-saga", "Сага и outbox", "Ноги и письмо вместе. Компенсация ≠ второй POST.", "middle", false),
      c("arch-eventstorm", "Event Storming и граница", "Факты в прошедшем. Касса и книга — разный SUCCESS.", "junior", true),
      c("arch-arc42", "arc42 и ADR", "Решение с датой. TOGAF — один этаж «зачем портфелю».", "middle", false),
    ],
  },
  {
    id: "career",
    title: "Карьера",
    kicker: "собес и тон",
    blurb: "Резюме, стол вопроса, system design, этика денег. Live — отдельный пункт, когда готовы к оценке.",
    cards: [
      c("car-intro", "Карьера и собес: с чего начать", "Кто страдает, чем измерим. Не «какую кнопку».", "intern", true),
      c("car-resume", "Резюме аналитика", "Факт и контур, не список курсов. Цифра и тикет.", "intern", true),
      c("car-interview", "Стол собеса", "Вопрос, ход, почему. Не таймер Zoom-школы.", "intern", true),
      c("car-sd", "System design на собесе", "Сначала деньги и ключ, потом микросервисы.", "junior", false),
      c("car-ethics", "Этика чужих денег", "Не врать сумму. Не прятать дубль ради KPI.", "intern", true),
      c("car-portfolio", "Портфель артефактов", "Then, схема, YAML, SQL. Не список курсов и не NDA.", "intern", true),
      c("car-cert", "IREB и IIBA: зачем", "Буквы если просят. Не зубрить вместо available.", "intern", true),
    ],
  },
  {
    id: "processes",
    title: "Процессы",
    kicker: "схема смены, не павлин",
    blurb: "BPMN 2.0 совместный, машина холда, дыры Figma, мобильный vs веб. Сначала кадр и состояние, потом кнопка.",
    cards: [
      c("proc-bpmn-collab", "BPMN 2.0: дорожки и компенсация", "ACS на своей дорожке. Void, не refund из OPEN.", "junior", true),
      c("proc-uml-hold", "Activity и State холда", "OPEN / CLOSED / VOID. SUCCESS — язык кассы, не холда.", "intern", true),
      c("proc-figma", "Figma и дыры передачи", "Нет кадра UNKNOWN — нет handoff.", "intern", true),
      c("proc-mobile-web", "Мобильный vs веб", "Тот же журнал. Дельта: жест, сеть, пуш.", "intern", true),
    ],
  },
  {
    id: "quality",
    title: "Качество",
    kicker: "NFR числом и запретом",
    blurb: "SLO на шов денег, STRIDE и PII, взгляд PCI на лог, WCAG как критерий кассы. Не лозунг «надёжно».",
    cards: [
      c("nfr-slo", "SLO, SLI, бюджет ошибки", "Мерим capture, не CPU. 409 — хороший код.", "junior", true),
      c("nfr-security", "STRIDE и PII", "Уже был JWT. Здесь угрозы и запрет полей в топике.", "junior", true),
      c("nfr-pci-log", "PCI глазами SA", "PAN и CVV не в лог, тикет, DWH. Не роль QSA.", "junior", true),
      c("nfr-wcag", "WCAG как NFR", "Клавиатура, имя кнопки, статус словом.", "intern", true),
    ],
  },
  {
    id: "bank",
    title: "Платежи",
    kicker: "конверт, карта, книга",
    blurb: "ISO 20022 против нашего IBAN, CP/CNP и 3DS, AML/KYC как Then, три числа глубже, правила сверки.",
    cards: [
      c("bank-iso20022", "ISO 20022, SWIFT, SEPA", "Чужой конверт. Suspense, не «похожий» счёт.", "junior", true),
      c("bank-cp-cnp", "CP, CNP и 3DS", "Присутствие карты. ACS не пишет ноги.", "junior", true),
      c("bank-aml-kyc", "AML и KYC как требования", "Мастер личности. Порог числом. След не в Slack.", "intern", true),
      c("bank-ledger-deep", "Ledger, available, hold — глубже", "Гонка, частичный capture, запрет UPDATE.", "intern", true),
      c("bank-recon", "Сверка: матчинг", "Ключ, потом сумма. Хвост не накидывать.", "junior", true),
    ],
  },
  {
    id: "softs",
    title: "Софты",
    kicker: "кто решает, как ведём стол",
    blurb: "RACI на фиче — один Accountable. Воркшоп 90 минут и скрипт эскалации, не @channel.",
    cards: [
      c("soft-raci", "RACI на фиче", "Один A на захват scope. Комплаенс не только I.", "intern", true),
      c("soft-workshop", "Фасилитация и эскалация", "Need к минуте 40. How в парковку. Один вопрос A.", "junior", true),
    ],
  },
];

export function trackById(id) {
  return TRACKS.find((t) => t.id === id) || TRACKS[0];
}
