import type { Achievement } from "@/types/content";

export const ACHIEVEMENTS: Achievement[] = [
  { id: "first-step", title: "Первый след", description: "Завершите любой модуль.", icon: "footprints", xp: 25 },
  { id: "intern-seal", title: "Печать Intern", description: "Пройдите все уровни Intern.", icon: "sprout", xp: 80 },
  { id: "junior-seal", title: "Печать Junior", description: "Закройте весь Junior-путь.", icon: "compass", xp: 100 },
  { id: "middle-seal", title: "Печать Middle", description: "Станьте самостоятельным Middle.", icon: "hexagon", xp: 140 },
  { id: "senior-seal", title: "Печать Senior", description: "Пройдите Senior до конца.", icon: "crown", xp: 200 },
  { id: "quiz-ace", title: "Безупречный квиз", description: "Наберите 100% в любом тесте.", icon: "sparkles", xp: 40 },
  { id: "practice-hand", title: "Рука практика", description: "Сдайте 8 практических работ.", icon: "pen-line", xp: 60 },
  { id: "drill-12", title: "Тренажёр", description: "Закройте 12 мини-игр.", icon: "swords", xp: 70 },
  { id: "lab-first", title: "Первая смена", description: "Пройдите миссию в зале практики.", icon: "briefcase", xp: 40 },
  { id: "lab-master", title: "Ночная смена", description: "Закройте 8 миссий зала.", icon: "moon", xp: 120 },
  { id: "quest-end", title: "Смена на контуре", description: "Доведите любой квест до исхода.", icon: "radio", xp: 50 },
  { id: "quest-clean", title: "Чистый контур", description: "Выкатите Wallet с ключом и честными статусами.", icon: "shield", xp: 90 },
  { id: "quest-world", title: "Три продукта", description: "Закройте квесты на трёх разных контурах.", icon: "globe", xp: 80 },
  { id: "quest-scribe", title: "Текст в контракте", description: "Три раза зафиксируйте свой текст в квесте.", icon: "pen-line", xp: 40 },
  { id: "streak-3", title: "Три дня в зале", description: "Заходите три дня подряд.", icon: "calendar", xp: 30 },
  { id: "streak-7", title: "Неделя аналитика", description: "Серия 7 дней.", icon: "flame", xp: 70 },
  { id: "combo-5", title: "Серия ударов", description: "5 верных решений подряд.", icon: "zap", xp: 40 },
  { id: "interview-ready", title: "Голос на собесе", description: "Разберите 20 вопросов интервью.", icon: "mic", xp: 50 },
  { id: "exam-pass", title: "Симуляция пройдена", description: "Сдайте финальный экзамен на 70%+.", icon: "scroll", xp: 120 },
  { id: "exam-master", title: "Мастер симуляции", description: "Экзамен на 90% и выше.", icon: "gem", xp: 180 },
  { id: "xp-500", title: "Путь открыт", description: "Наберите 500 XP.", icon: "flame", xp: 30 },
  { id: "xp-1500", title: "Легенда зала", description: "Наберите 1500 XP.", icon: "trophy", xp: 80 },
  { id: "path-complete", title: "Полный путь", description: "Завершите все модули академии.", icon: "orbit", xp: 300 },
];
